externalSecret:
  dockerRegistry: docker-registry
  googleOauthJson: google-oauth-json
  cookieSecretKey: cookie-secret-key
  jwtSecretKey: jwt-secret-key
  postgresDbUrl: postgres-db-url
webStatic:
  image: davemorse981/ccc-web-static
  tag: 0.0.1
  replicaCount: 1
  service:
    port: 5173
webApi:
  image: davemorse981/ccc-web-api
  tag: 0.0.1
  replicaCount: 1
  service:
    port: 8000