#!/usr/bin/env bash
# This ugly script creates a docker registry secret for the ccc-dev namespace.
# The aptly named secret `docker-registry` is then namechecked by helm (though the name of the secret is configurable)

# Creating docker registry secrets in helm is a pain. 
# Instead this shows how to create it from the cli with values.
# You may have to customize this e.g. for a different namespace or if secrets are stored in a different manner. 

set -e

kubectl create secret docker-registry docker-registry --namespace ccc-dev \
  --docker-username=$(op read op://Private/dockerhub/username)\
  --docker-email=$(op read op://Private/dockerhub/email) \
  --docker-password=$(op read op://Private/dockerhub/read-only-service-pat) \
  --dry-run=client -o yaml