#!/usr/bin/env bash
# This example script creates a secret for the ccc-dev namespace.
# Then the name of the secret is fed into the helm chart for use by the web-api. 

# This fits the pattern of make-docker-registry-secret, but could be folded into helm configuration 
# too, I guess. Which might be helmier. 

set -e
kubectl create secret generic google-oauth-json --namespace ccc-dev \
  --from-literal=google-oauth-json="$(op read op://Private/calendar-credential-confuser/JSON)" \
  --dry-run=client -o yaml