apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-static-{{ .Release.Name }}
spec:
  replicas: {{ .Values.webStatic.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      role: web-public
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        role: web-public
    spec:
      imagePullSecrets:
        - name: {{ .Values.externalSecret.dockerRegistry }}
      containers:
      - name: nginx
        image: "{{ .Values.webStatic.image }}:{{ .Values.webStatic.tag }}"
        imagePullPolicy: Always
        env:
        - name: BE_SERVICE_NAME
          value: clip-web-api-{{ .Release.Name }}
        - name: BE_SERVICE_PORT
          value: "{{ .Values.webApi.clusterIP.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: loba-web-static-{{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.webStatic.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name }}
    role: web-public
