apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-static-{{ .Release.Name }}
spec:
  replicas: {{ .Values.webStatic.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: nginx
        image: "{{ .Values.webStatic.image }}:{{ .Values.webStatic.tag }}"
        imagePullPolicy: Always
      imagePullSecrets:
        - name: {{ .Values.externalSecret.dockerRegistry }}
---
apiVersion: v1
kind: Service
metadata:
  name: web-static-{{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.webStatic.service.port }}
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Release.Name }}