apiVersion: v1
kind: Service
metadata:
  name: dev-load-balancer
  namespace: confusedb
spec:
  type: LoadBalancer
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: confusedb